[env]
MISE_USE_VERSIONS_HOST = "0"

[tools]
lua = "5.4"
stylua = "latest"

[tasks.format]
description = "Format Lua scripts"
run = "stylua metadata.lua hooks/"

[tasks.ci]
description = "Run all CI checks"
depends = ["lint", "test"]